# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 449463aec5523be8542b3b66447b5b1fee20749a28bae53407ebca1b62b008059765be87c3c88eea6e2443825c263f18e10006bacb87bf41d87945cb192b5734

test:
  secret_key_base: 279ab43325d4b78a9674f0440e1de904506b6948831831e5e9c21d0438dde8a1c90210f3a07bc50470bb61726639c4c845eff94ed6187fdf1a2d178abfb39b56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
